import os
from pathlib import Path


STORAGE_PATH = Path(os.environ.get("STORAGE_PATH", "data"))
DB_PATH = Path(os.environ.get("DB_PATH", str(STORAGE_PATH / "sync.db")))

PROTOCOL_VERSION = 1
CRYPTO_PROFILE = "argon2id-xchacha20poly1305-v1"
GITHUB_CLIENT_ID = "Ov23liyv3nEucG7oMHNE"
MAX_HTTP_BODY_BYTES = 25_165_824
MAX_CIPHERTEXT_BYTES = 16_777_232
MAX_PLAINTEXT_JSON_BYTES = 15_728_640
IDEMPOTENCY_RETENTION_SECONDS = 604_800
MAX_BACKUP_RETENTION_DAYS = 30
SESSION_TTL_SECONDS = 900
