import os
from pathlib import Path


STORAGE_PATH = Path(os.environ.get("STORAGE_PATH", "data"))
DB_PATH = Path(os.environ.get("DB_PATH", str(STORAGE_PATH / "sync.db")))
ADMIN_TOKEN = os.environ.get("ADMIN_TOKEN", "")

PROTOCOL_VERSION = 1
CRYPTO_PROFILE = "argon2id-xchacha20poly1305-v1"
AEAD_NAME = "xchacha20poly1305-ietf"
CODEC_NAME = "json-pad64k-v1"
KDF_NAME = "argon2id"
KDF_VERSION = 19
KDF_MEMORY_KIB = 65_536
KDF_ITERATIONS = 3
KDF_PARALLELISM = 4
PAD_BLOCK_BYTES = 65_536
MIN_CIPHERTEXT_BYTES = PAD_BLOCK_BYTES + 16
GITHUB_CLIENT_ID = "Ov23liyv3nEucG7oMHNE"
MAX_HTTP_BODY_BYTES = 25_165_824
MAX_CIPHERTEXT_BYTES = 16_777_232
MAX_PLAINTEXT_JSON_BYTES = 15_728_640
IDEMPOTENCY_RETENTION_SECONDS = 604_800
MAX_BACKUP_RETENTION_DAYS = 30
SESSION_TTL_SECONDS = 900
